In [1]:
import numpy as np
import tensorflow as tf

텐서플로의 데이터 포맷 : 
- (m, n) , m:데이터 갯수, n:특징 수
- 시계열/시퀀스 데이터 : (m, t, n) , m:데이터 갯수, t:시간, n:특징 수 
- 영상 (m, h, w, c) , (갯수,높이,너비,채널)    ,  CAFFE (m,c,h,w)
- 커널 (h, w, c, m) 

In [12]:
x = np.arange(1, 10).reshape([1,3,3,1]).astype(np.float32)  
x.dtype
x[0, :, :, 0]

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

맥스 풀링, ksize, stride = [2,2]  SAME(zero 패딩)  를 주로 사용합니다  

In [25]:
out = tf.nn.max_pool(value=x, ksize=[2,2],strides=[2, 2], padding='SAME')#VALID or SAME, kernel = filter

In [26]:
sess = tf.InteractiveSession() # .eval() 로 값을 바로 볼 수 있습니다

In [27]:
out.eval()

array([[[[5.],
         [6.]],

        [[8.],
         [9.]]]], dtype=float32)

In [37]:
kernel = np.arange(1,5).reshape([2,2,1,1]).astype(np.float32) #(h,w,c,m)

In [38]:
x[0, :, :, 0]

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [39]:
kernel[:,:,0,0]

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [48]:
out = tf.nn.conv2d(x, kernel, strides=[1, 1], padding='SAME')

In [49]:
out.eval()

array([[[[37.],
         [47.],
         [21.]],

        [[67.],
         [77.],
         [33.]],

        [[23.],
         [26.],
         [ 9.]]]], dtype=float32)

In [43]:
np.array([5,6,8,9]) * np.array([1,2,3,4]), np.sum(np.array([5,6,8,9]) * np.array([1,2,3,4]))

(array([ 5, 12, 24, 36]), 77)